### ISSUE TITLE
Include screenshots for README

### ISSUE THREAD

**Issue by MarkOSullivan94** [Elleo/baby_elephant#1]
Hey @Elleo 👋 

Excited to see where this project will go but without screenshots I have no idea how far into development it is without loading up the code myself

Would really help having some screenshots along with tickets within the Issues section so I can watch the progression over time 😄 

Wishing you all the best with this project

**Comment by Elleo** [comment]
Hi @MarkOSullivan94!

Thanks for the prod, I've updated the readme with a roadmap to give a better indication of where the project is at currently and added an image showing it running on a watch
